export default "9-10 m: mmmmnxmmmwm\n" +
  "6-8 w: wpwwhxnv\n" +
  "4-6 n: trwpnnnvq\n" +
  "12-15 p: zfpmpphpgghpppppppp\n" +
  "5-10 z: bqlbzfzzzbzwsz\n" +
  "7-15 m: mmkvmwmklnqpmggbgn\n" +
  "2-3 z: zzzzzz\n" +
  "9-11 f: fffffffffffff\n" +
  "8-10 l: lllfllllll\n" +
  "1-3 l: llll\n" +
  "2-9 m: mjmmmmmmmm\n" +
  "3-4 m: kmmm\n" +
  "2-11 f: fjdfffmffffrff\n" +
  "14-16 m: mmmmtmmmmmlmmmdmmm\n" +
  "1-5 k: kmvkkkkkq\n" +
  "5-7 g: mghggkgg\n" +
  "5-19 t: tdltgttttqmtjtjgxmp\n" +
  "5-7 r: rrrrrrsrrrrrrrrrrr\n" +
  "15-16 q: qqqqqqqqqqqqqqqqn\n" +
  "1-5 q: qqtpqk\n" +
  "12-13 t: qzgpttrtlttjd\n" +
  "4-12 q: jsvvqxtqhqqgntvvqqpq\n" +
  "13-17 f: ffffffffffffrfffff\n" +
  "14-15 r: rdxktqpprdrshdttg\n" +
  "8-10 t: ttpftttkppxttthhb\n" +
  "1-3 l: hlwlpnc\n" +
  "16-17 n: ntzqkmsnwtqjwtdnn\n" +
  "3-5 m: jcmxmnpfwmxvmdd\n" +
  "16-19 c: cmcccccckkccvcckzccc\n" +
  "6-9 g: gcgggggfgln\n" +
  "5-9 r: rrrkxrrrq\n" +
  "1-3 t: dxcsbvzrrtcfwrh\n" +
  "1-3 x: xpxdbrhd\n" +
  "2-3 m: mpfx\n" +
  "14-17 j: fcjjpjjnmjptnjmjj\n" +
  "4-5 x: xxxxr\n" +
  "10-13 n: nnnpnnnnntntjn\n" +
  "11-12 j: hzjkzgjjgjbvvjjhh\n" +
  "8-17 f: ffhrvbzxfzffhzznfcj\n" +
  "1-5 p: ppppppp\n" +
  "1-4 q: vqqnqjqqwm\n" +
  "3-8 r: rzrrrgtr\n" +
  "8-9 v: vvtnxvdvs\n" +
  "16-17 s: dspssssssscsssssssss\n" +
  "10-13 t: tttttttttttttt\n" +
  "1-3 s: dslp\n" +
  "3-6 w: wglwwxwwwwwww\n" +
  "1-6 p: nppppc\n" +
  "6-10 t: tttztstttbnft\n" +
  "8-13 j: cztwvjhjdmbbj\n" +
  "1-7 w: wwnwzwwbbwwwswwwwtw\n" +
  "7-17 q: qqqqqqbqqqqqqqqqq\n" +
  "4-11 v: vvvvbvvvvvrcvwvvvvv\n" +
  "8-13 d: dddddbhzdddddd\n" +
  "13-16 q: qqqqqnqqqqqqcqqw\n" +
  "5-6 m: mmmmnm\n" +
  "10-18 g: jdpgfxfqlgtcckxsrgn\n" +
  "3-4 b: bbgmb\n" +
  "12-14 l: lkklrcllxlllllk\n" +
  "6-7 h: kvxlzrvmd\n" +
  "3-4 b: kbbg\n" +
  "3-5 v: glgvs\n" +
  "3-6 x: xxxxxxx\n" +
  "1-2 z: zzfnb\n" +
  "5-6 b: bqbbbx\n" +
  "3-5 j: wjvsf\n" +
  "3-8 x: fxxxkxxbxhxnx\n" +
  "11-12 s: vsssspcmqsbzsssss\n" +
  "3-4 v: nvvvc\n" +
  "9-10 p: pppppppppp\n" +
  "7-8 l: pfclnccfn\n" +
  "14-17 c: jcrjhgcccccnsccpc\n" +
  "3-4 p: pjgcpxt\n" +
  "4-8 l: wvlrptdftlpw\n" +
  "6-10 f: hdnffrxfrf\n" +
  "2-5 s: ssssj\n" +
  "10-13 x: xvlcrccxxxbxh\n" +
  "3-4 w: wwwdw\n" +
  "9-15 g: gggggggggggggggg\n" +
  "10-11 f: flxvfffffwqk\n" +
  "5-6 l: lllltvlll\n" +
  "8-9 t: vpdrntgdr\n" +
  "11-12 c: bpxsnvhvfcprpwz\n" +
  "7-8 f: wpgfvvzb\n" +
  "2-6 p: dmccpk\n" +
  "7-11 d: kwdblcxdrmr\n" +
  "3-4 g: ggfzgggg\n" +
  "7-9 h: hhhzcvdnz\n" +
  "4-8 l: ttljxlxlw\n" +
  "12-15 x: xtwwxxxcxxxxxxsx\n" +
  "10-13 d: ddbhkdddddddd\n" +
  "1-4 j: jjvtmc\n" +
  "8-11 b: bbxcrjbmnnbmxfq\n" +
  "3-4 h: hhhh\n" +
  "5-7 n: nnnqwvgn\n" +
  "3-5 q: qxlqvqq\n" +
  "4-9 k: kkkkkkkkkkk\n" +
  "5-8 p: spppxppwpppprppp\n" +
  "3-12 q: qtkqqpqtqqqqqqqqqqq\n" +
  "16-17 x: xzhxxxxxqnxmhxxpd\n" +
  "12-15 q: rsrhzrghndsqslqnp\n" +
  "2-6 z: rzzpzz\n" +
  "2-4 m: mmbm\n" +
  "4-5 g: gfgfq\n" +
  "1-6 t: stttsh\n" +
  "4-5 h: hlhnm\n" +
  "12-13 d: dddddddddddpd\n" +
  "9-10 h: ghhhhhhhkchh\n" +
  "10-15 r: rvgxrrcrrwrrrrtlrrr\n" +
  "5-10 l: qltclnnblcrlv\n" +
  "11-17 p: ppqpppvjbrpppqpppjw\n" +
  "9-12 g: xghzsgmkggtg\n" +
  "13-15 t: jtdkhqttstxbztstt\n" +
  "14-18 c: chcvxpcxccxckhcddh\n" +
  "12-14 d: ddddddddsddddd\n" +
  "4-8 l: rsdllblllxl\n" +
  "4-9 m: xmrzbmrmhbsm\n" +
  "2-3 s: ptcp\n" +
  "5-8 p: mtxhpvkpkrzhhjxpp\n" +
  "4-6 w: wwwdwj\n" +
  "4-6 w: wwwlwf\n" +
  "6-7 l: zllntlr\n" +
  "10-14 d: dqdddddddndddvddd\n" +
  "2-6 f: dfpjwfgrfwlsc\n" +
  "3-5 n: lnnxvq\n" +
  "4-19 b: bbbbqbbbbbbjbbbsbbbb\n" +
  "4-12 s: mmlmthslfcnnrwkh\n" +
  "2-7 d: ddddddd\n" +
  "3-7 j: kpjwjjj\n" +
  "7-8 p: pcmchppp\n" +
  "4-7 f: fffvffgf\n" +
  "4-7 d: ddmdfcv\n" +
  "13-14 w: wjwmwwxwfmpdpf\n" +
  "5-7 d: ddrdmsh\n" +
  "4-5 r: rrrrrr\n" +
  "4-5 g: ngsvg\n" +
  "7-13 g: gggggggfggggggjg\n" +
  "6-10 m: hbsqkpmfzss\n" +
  "8-10 p: kppkdpptpmpnpl\n" +
  "3-4 l: llll\n" +
  "11-12 s: ssssssssssqksq\n" +
  "15-16 d: gdmdwdrzdkctddzv\n" +
  "7-13 d: ddddddddqdddjd\n" +
  "7-8 t: tdtdrglm\n" +
  "3-6 s: sskssz\n" +
  "2-3 n: nbnmrnxxfwqbdh\n" +
  "1-4 l: wlxlllllllllllnpl\n" +
  "7-8 v: khcxvvfd\n" +
  "14-15 j: jjjjjjjjjjjjjbf\n" +
  "1-7 n: ndncltg\n" +
  "1-5 l: dllzmg\n" +
  "3-4 p: zpzmp\n" +
  "1-6 b: sbbbsb\n" +
  "11-13 x: twcxxxxcxxxxd\n" +
  "3-4 r: rrrtv\n" +
  "1-9 z: kzvlzlnznzlhbdp\n" +
  "5-11 q: qfbqbqnsjds\n" +
  "4-5 b: wcjbb\n" +
  "2-4 b: bdbn\n" +
  "3-12 g: zftzmsbsjgggw\n" +
  "11-14 h: hkhhhdhhhdfhhhh\n" +
  "1-2 z: zzbz\n" +
  "6-15 z: zznzzzzzzzzzzzzzzzzz\n" +
  "6-9 j: jjjjjwjjm\n" +
  "2-3 h: glghhh\n" +
  "16-17 r: rhhdnrjrrbrgnrqjb\n" +
  "2-12 j: jzjjchndjjbcfhmqkmn\n" +
  "1-4 n: dnnn\n" +
  "7-12 w: wswwwqmswqwcl\n" +
  "3-5 g: ggvgz\n" +
  "1-3 c: ccccmczccq\n" +
  "4-8 k: rhckkkkksvkdkmkkvbrk\n" +
  "7-11 j: gjwjhjjpsfqxnjd\n" +
  "3-4 n: ndnjn\n" +
  "3-4 b: gsbhb\n" +
  "4-5 z: zzzzzz\n" +
  "2-12 f: zltmcbkcvlsfjsm\n" +
  "8-11 g: gggggggtxgmg\n" +
  "8-11 l: lllllllllllll\n" +
  "1-18 d: ddmlltqflhkpjdxrwdn\n" +
  "3-4 h: hdhhh\n" +
  "3-11 w: djwsxklbrbptcfcwcrch\n" +
  "7-9 m: hshmlmmmmv\n" +
  "11-17 d: dtcdddddhdjprmqdjb\n" +
  "3-6 c: ccjccccv\n" +
  "12-16 r: rrrrrrrrrrrrrrrrr\n" +
  "4-5 p: hvpnc\n" +
  "2-11 z: zzznvrzzvzzz\n" +
  "6-7 s: szfswss\n" +
  "19-20 p: pppppppppppppppppppp\n" +
  "1-11 b: bzkqmnbbwmkczz\n" +
  "15-17 d: ddddddddddddddddd\n" +
  "5-12 s: xsskshskfvkrmsssv\n" +
  "2-17 r: rrrrrrrrlrzrrwrrr\n" +
  "5-8 c: cccclccn\n" +
  "7-11 k: fnktjpzbcckjnqvmmnl\n" +
  "4-5 c: cdzhcfvsc\n" +
  "2-8 f: mfsfrfbs\n" +
  "11-12 r: rqhjgnsrrrlj\n" +
  "5-7 r: vbfjpzrr\n" +
  "2-4 d: dwjl\n" +
  "5-9 f: ddffrrfffffnfjr\n" +
  "1-12 h: whghdlghthlxjmg\n" +
  "5-18 p: lpppqplhsxpppppppqx\n" +
  "9-13 q: xqkzksbsrgsqq\n" +
  "13-15 l: llllllllllllllll\n" +
  "9-11 p: whpfjshkxcjf\n" +
  "6-7 g: gggggfbg\n" +
  "10-11 b: bbbbbbtbbbb\n" +
  "2-4 n: tnhn\n" +
  "12-13 q: fqqqqqqqqqxfvvqq\n" +
  "6-7 d: ctddrqw\n" +
  "6-8 n: nzwnnzvnnnnrr\n" +
  "10-14 w: qjlxjwdqzgthzs\n" +
  "6-14 n: qnpznqnqdmnnnmcmqrbh\n" +
  "6-19 r: lrrmrprlrbrpztrrrrr\n" +
  "3-7 p: pwppghpp\n" +
  "6-12 l: llllllllhllllllll\n" +
  "11-12 n: nnznnnhnnnnn\n" +
  "17-19 b: bbnbbbbbbbbbbbbbrbj\n" +
  "8-11 d: dfddfdxdddd\n" +
  "4-5 w: wwwxl\n" +
  "2-8 v: xzvvvvvcvbvlz\n" +
  "6-7 t: ktttwct\n" +
  "2-4 l: wltlc\n" +
  "5-12 d: kqmpddtfzlfddsd\n" +
  "3-4 r: rrrg\n" +
  "1-4 k: dkks\n" +
  "3-6 v: vvtvvh\n" +
  "14-15 c: ccscchbcccccccc\n" +
  "2-8 v: svvvhsvv\n" +
  "11-14 g: gggggggggggggggp\n" +
  "8-10 v: vvvvvvvvvvv\n" +
  "7-13 g: gggggggggccggg\n" +
  "8-10 v: vvvvvvpvvv\n" +
  "1-3 d: dddd\n" +
  "5-6 w: vrnpcw\n" +
  "9-12 w: wwgwfwwwwgmw\n" +
  "7-11 w: wwwwwwwwwwww\n" +
  "1-4 f: fwft\n" +
  "6-8 n: cnnbpnnnctnnvnldnj\n" +
  "8-17 r: jrrmrrrfrrdrrjrsdr\n" +
  "5-7 r: rrrrhrtr\n" +
  "5-6 z: nxwtzzwlsmngkjzjgs\n" +
  "5-6 q: qqqqqq\n" +
  "4-5 c: sskrxc\n" +
  "3-9 f: sjfstwfpffcdhfftbfvt\n" +
  "1-4 z: zzzzzzzzzzzzzzzzzzz\n" +
  "5-6 f: xmnfffb\n" +
  "1-3 z: nzdzzz\n" +
  "8-13 s: sgsgbsssbsbsssk\n" +
  "5-7 v: vlbqjhrmbvw\n" +
  "9-10 w: wwwwwwwwgfwxwwwjwwww\n" +
  "5-7 n: nkvqnnnn\n" +
  "3-14 b: mzkkbbcbbmgxvbp\n" +
  "18-19 h: hhhhhhhhhhhhwhhhhhh\n" +
  "3-6 g: ggjvggggm\n" +
  "11-14 c: ccccjclccccdcccncc\n" +
  "5-7 x: xlckxxx\n" +
  "2-5 l: lrlll\n" +
  "10-12 t: tttttdtttztjt\n" +
  "1-4 c: cpkctsjp\n" +
  "6-11 c: cccccccccccc\n" +
  "6-8 f: cffvnrkfqmfffr\n" +
  "8-10 c: cccmcccccc\n" +
  "2-4 m: fdhdkxfmlz\n" +
  "5-7 g: gggggjgggg\n" +
  "13-14 v: vkhvpxdthvdvnrl\n" +
  "6-12 c: cccgcrcchccqzsqsc\n" +
  "7-8 w: wwwwwwcrwm\n" +
  "12-15 s: smmfsspsspsswss\n" +
  "7-14 p: pxppsmppppppgqmpppp\n" +
  "6-13 z: pjzzdzshcdgzcslr\n" +
  "8-10 q: qqqqqqqqqqq\n" +
  "2-4 p: ppppp\n" +
  "10-15 t: hqtttttqtltvttsttt\n" +
  "8-10 g: qrvfmmggsr\n" +
  "6-7 d: dddvdvdd\n" +
  "3-4 q: qqkcq\n" +
  "1-2 l: llgwzclzl\n" +
  "7-8 h: hhhhhhgfhh\n" +
  "2-4 f: fkcpq\n" +
  "3-5 r: rrrrrrr\n" +
  "5-7 p: pppppppkppwpk\n" +
  "4-5 j: jgcjj\n" +
  "8-9 g: gggggggggggvggg\n" +
  "7-10 p: pplppptnpn\n" +
  "8-9 p: pppppppwpp\n" +
  "4-5 k: skkkk\n" +
  "11-17 f: fkkffknfspfkxffvf\n" +
  "3-14 x: xxmxxxxxxxxxxjxxx\n" +
  "2-4 r: ndjpbrgjwsfpqlnrcr\n" +
  "8-10 w: dgwzwwwdwtww\n" +
  "6-7 l: mvdftllwnzxdwhcvl\n" +
  "9-11 v: vvvvvvvvmvv\n" +
  "10-11 z: pzzzlsfzppzzzzzlz\n" +
  "7-8 w: wwwwwwww\n" +
  "3-5 r: rrprrr\n" +
  "10-11 z: zzzzzzzzzzzvz\n" +
  "7-8 q: qqqqqqzmqz\n" +
  "9-10 g: dggggggrqtgg\n" +
  "4-10 c: cccfcccccz\n" +
  "5-12 g: hfwkqmgxszhl\n" +
  "1-4 q: dqqrqq\n" +
  "1-10 v: qvvvvvvvgvvvv\n" +
  "6-7 l: rhllzllll\n" +
  "2-4 s: sssssq\n" +
  "12-16 r: rrrrrrrrrnrrrrrrrrrr\n" +
  "1-5 w: wgwzc\n" +
  "12-13 l: llhlldlmlllllll\n" +
  "4-8 b: bbbbbbbkb\n" +
  "1-5 p: ptpsp\n" +
  "4-6 d: mjvdld\n" +
  "2-6 m: mmvgtms\n" +
  "3-5 d: rrdfdrddzw\n" +
  "1-5 s: ssssss\n" +
  "8-11 f: qfflffffmffffffftx\n" +
  "2-10 x: xxxxxrxxxxvxsxvxgxwx\n" +
  "3-5 v: vkgqv\n" +
  "16-17 h: hthhhhhhhhhhhhhrh\n" +
  "4-5 b: bqplb\n" +
  "3-5 b: txbbbqsbbksmbp\n" +
  "16-17 q: nqjqqqqqqjdqqqqgl\n" +
  "4-5 x: xlxcfxx\n" +
  "15-16 x: xxxxxxxxxxxxxxmg\n" +
  "15-17 t: tkkttwttttttttttttt\n" +
  "6-7 v: vvvfvvvvvvvvvvvvvvvv\n" +
  "9-13 j: jjjjjjjzvjjjpj\n" +
  "6-11 s: sscsscswsfnsss\n" +
  "1-2 c: cnpl\n" +
  "17-18 v: vvvvvsvhvrvvvhvvqc\n" +
  "6-7 j: jjbjjjjstjg\n" +
  "5-14 g: gggmxgngggngggl\n" +
  "2-4 b: bmbwbs\n" +
  "11-16 v: cvrtvnvqvvcvvvvwv\n" +
  "16-19 c: chccgvlclcnncdfcxcn\n" +
  "1-2 g: rngb\n" +
  "5-7 j: jjjdfjjjjj\n" +
  "5-6 g: ggfghx\n" +
  "1-2 m: pmgndcmg\n" +
  "10-12 w: cwwwwjhznwcwswl\n" +
  "1-2 z: zzzzzz\n" +
  "4-5 z: hxmzh\n" +
  "1-2 t: thwxshrtldtvg\n" +
  "8-16 h: hhhhhhhhhhhhhhhhhhh\n" +
  "6-18 q: qqqqmqqqqbqxqqqqqqqq\n" +
  "4-5 g: gjjgq\n" +
  "3-12 x: txxxxvxjnxxxxxskhh\n" +
  "1-15 f: fffnqfwrffhffff\n" +
  "7-10 g: gpggzgggdkk\n" +
  "4-8 v: vvvgbvvbzv\n" +
  "1-6 n: cnqnnnb\n" +
  "1-3 k: skzkkdk\n" +
  "10-11 z: zzzzzzzqxhzt\n" +
  "7-16 p: sppdxpdzppppdpvj\n" +
  "9-10 n: nnnnnnnnfnnnnn\n" +
  "3-9 v: vhvtkxzxvjp\n" +
  "7-15 h: rtvchhhhhpdlzthz\n" +
  "5-10 d: njqvdnrdddvptdf\n" +
  "1-5 t: ttgzttll\n" +
  "3-7 l: zwzbwtdllsznz\n" +
  "5-8 t: btvtthtttd\n" +
  "6-7 t: tthtttb\n" +
  "3-17 s: zslvsbrlnqshsrgss\n" +
  "4-7 f: fffffff\n" +
  "2-5 v: vvvvgv\n" +
  "2-4 r: crrr\n" +
  "8-9 k: fklhhzskk\n" +
  "5-9 d: dbddjdddkddddd\n" +
  "2-5 z: svzkzbbkmj\n" +
  "2-4 f: lgwf\n" +
  "2-4 q: mvrzbd\n" +
  "6-13 r: trrrrrrrdgrbrrrjrrx\n" +
  "16-17 g: ggggggggggggggggg\n" +
  "6-15 p: mhpcppnfnplhzjphs\n" +
  "5-10 l: nvllkslllxlllzlj\n" +
  "3-8 l: dclccbslwlslqlll\n" +
  "4-8 v: vvvvvvvv\n" +
  "14-16 v: svvvnvvxvvvqvvvn\n" +
  "8-13 z: zzzzzrmzszfzpzzznzf\n" +
  "9-11 f: ffffffffnfc\n" +
  "4-7 q: qsxfqqc\n" +
  "2-6 h: nhrnhhx\n" +
  "8-12 k: mbkgxkvxqqkk\n" +
  "13-14 c: lclkmkmcdxscww\n" +
  "4-5 p: pppppp\n" +
  "2-4 l: lbzmpv\n" +
  "3-4 g: glggngprsgr\n" +
  "10-15 b: bbbbbbbbbbbbbbbbbbb\n" +
  "11-17 z: zzzzzzzzzzxzzzzzxz\n" +
  "7-8 q: frvqpggq\n" +
  "9-10 f: fffffkbffff\n" +
  "3-12 j: jjjjjjjjjjjjjj\n" +
  "4-5 j: jjbkd\n" +
  "1-2 m: nmdmmmmmmm\n" +
  "14-16 w: wwwwwwwwwwwwwwww\n" +
  "5-9 r: rrkrrwhrrr\n" +
  "2-3 h: hcfh\n" +
  "15-17 w: zmwwwwwwgwwwwwwvwwww\n" +
  "8-13 r: lzfczkplgdpqz\n" +
  "13-14 z: qzzczzkgzzzmztcz\n" +
  "8-9 k: kkstkcrkkmjbklk\n" +
  "12-13 w: bkxwwwwwzwwwwwwwswx\n" +
  "7-8 x: xxxxxxlvxx\n" +
  "2-4 l: wlllsllll\n" +
  "5-6 c: cmccccccv\n" +
  "3-4 p: ppvs\n" +
  "5-12 s: fssssldsssxpvsx\n" +
  "5-12 g: jvqrggdbglpgggkkxgg\n" +
  "7-8 g: ggxgnjgggzbgjg\n" +
  "8-9 p: pcppppppp\n" +
  "5-14 f: bfffhffffhfsfff\n" +
  "2-5 f: fffffff\n" +
  "3-12 x: pxxxxxqkxhdqk\n" +
  "10-13 r: rrrrrrrrrrrrrrrrrr\n" +
  "6-15 x: nmxsfhbcvgvhxlx\n" +
  "5-9 v: vvvvvvvvv\n" +
  "3-5 s: ssdsss\n" +
  "10-15 n: cncwgtrhbnxpkwqzhvdn\n" +
  "10-13 j: nfjjzvzjjqtpx\n" +
  "12-13 j: jjjhjjjjjjjqr\n" +
  "9-12 h: hhhhhhlhhhhhhh\n" +
  "9-11 l: ljlllllfgvlll\n" +
  "1-4 p: gbpp\n" +
  "6-7 x: xtxxxhj\n" +
  "2-17 v: vvvvvcvchvvtpvvvp\n" +
  "1-5 c: bcccgc\n" +
  "2-5 p: ppbxp\n" +
  "2-3 w: wwwjwpjdjw\n" +
  "12-13 p: pmcppzwpkppppppppd\n" +
  "17-18 w: zgbwwwwzdwwswfxcgn\n" +
  "6-14 z: wzlzbdzzzzmzqspbcn\n" +
  "9-15 q: cttgqzglzxdqjhd\n" +
  "1-7 j: rgjrjjjjj\n" +
  "6-9 t: tttttxtttttt\n" +
  "3-5 d: rqkfq\n" +
  "3-12 c: cckwqckkcxcmwvnkz\n" +
  "7-8 z: zzkzdztgzz\n" +
  "3-5 t: wttttt\n" +
  "15-19 b: bbbbbbbbbpbbbrbbbtb\n" +
  "10-11 p: ppppppppprspphppp\n" +
  "5-7 v: nvqvbrfbd\n" +
  "6-8 n: vnnbhgnhn\n" +
  "7-11 r: prfrrhshrszrssr\n" +
  "4-5 z: qrszzht\n" +
  "7-9 z: zzzzzczzzzzz\n" +
  "2-3 l: lxtb\n" +
  "8-10 f: ffffffrfff\n" +
  "10-11 q: qqbgqqqcqqqq\n" +
  "2-9 l: gmflclltxcllzm\n" +
  "8-13 k: xkdglwzksvvdsjzp\n" +
  "7-8 h: hjkbfhsc\n" +
  "13-14 x: xxxxxxxxtxxxjbx\n" +
  "5-14 k: kkgkkkkkkkkkkkkkk\n" +
  "11-13 g: gwpggggggvxgzggg\n" +
  "4-6 j: jjjjfj\n" +
  "2-3 b: bxfb\n" +
  "1-2 k: kkkp\n" +
  "9-17 g: ggggggggkggggggghggg\n" +
  "3-4 p: nzpb\n" +
  "5-6 f: fbtfffv\n" +
  "4-10 h: hhhrhhhhhhh\n" +
  "3-11 d: wtddsbhwgfjmtlb\n" +
  "8-9 n: nnnnnnqrm\n" +
  "9-14 c: vchcclvtncscczbccw\n" +
  "7-9 q: qqqqqnlqqqqq\n" +
  "12-13 k: kkkkkckkkkkdh\n" +
  "4-9 v: vvvvvvvnvvvv\n" +
  "2-5 z: hhkzmwhzdfczf\n" +
  "4-5 q: qqqqq\n" +
  "4-12 g: gggggggggggggg\n" +
  "15-16 s: tnrtkspsszsmsmvs\n" +
  "13-16 h: hhhhhhhhhhhhmhhjhhhh\n" +
  "7-9 f: nhkmvtmfdcnfxflk\n" +
  "10-12 t: ttttttttsltw\n" +
  "1-5 t: nttttt\n" +
  "7-8 q: qqqqntqbfqq\n" +
  "6-10 z: zzzzzzzzzrz\n" +
  "10-17 k: kkkkkrkkpkkkkxqvkkdk\n" +
  "2-6 w: wqswjnwkx\n" +
  "9-18 l: fvhwjrrvnfzqvvhdwkpj\n" +
  "2-5 t: rqpxmqmnswvbtp\n" +
  "15-19 l: lfhlllllcbklgblllll\n" +
  "12-13 x: lxzvxxxxxxxrcxxtxxx\n" +
  "4-5 n: nngnb\n" +
  "5-14 j: jjjjjjjjjjjjjx\n" +
  "3-4 q: nqqqb\n" +
  "15-16 p: ppvpppppppppdpfqp\n" +
  "2-10 k: kkkkkkkkkkk\n" +
  "7-8 l: mllllllc\n" +
  "19-20 w: wwwwwwwwwwwwwwwwwhjb\n" +
  "2-4 t: rzmdfqjv\n" +
  "12-13 g: gggkggggvgvgtgg\n" +
  "7-12 b: qtjbzqbxbvsbwz\n" +
  "6-16 d: wmpjjddmtctmxbqd\n" +
  "13-15 c: fcznfkxzkftcfcfj\n" +
  "19-20 n: nnnxnnnnnnnnnnnnnnnn\n" +
  "6-8 x: gmgxxjxmxx\n" +
  "4-6 q: qqqqqpqqqdqqqqqq\n" +
  "3-5 c: cbcdc\n" +
  "6-7 k: ktwkqrkfmkpkkt\n" +
  "9-12 p: ppppppppqpwpp\n" +
  "16-20 c: cccccccccccpfccdcbcl\n" +
  "6-9 q: qqqqqzqqtfq\n" +
  "12-15 w: wwpwwwvrwwwwwzs\n" +
  "9-10 d: zddddhdfdd\n" +
  "11-12 c: cclkzqccxbccglgc\n" +
  "6-11 v: fzswbvbvddvpw\n" +
  "4-11 j: vnkjmztfjvj\n" +
  "2-3 h: jhhp\n" +
  "8-9 r: rrrrrrrrr\n" +
  "1-10 d: dddqdxdxdv\n" +
  "3-9 m: cmmpvmmhmmx\n" +
  "6-7 m: kpxtcmw\n" +
  "2-13 s: scjxbvrxfldhvf\n" +
  "3-11 w: wftqlhxsqhkwxwscrgvp\n" +
  "2-3 r: rrrq\n" +
  "1-2 t: tttd\n" +
  "6-7 b: pbbbbbbbbb\n" +
  "2-6 p: fkxlxnwpmxgtzv\n" +
  "12-14 w: wwlwwclgwwwwwxwwm\n" +
  "4-5 q: qqqkwq\n" +
  "11-16 q: qqqqqqqxqdqqqqqn\n" +
  "2-3 s: sgmmkxgs\n" +
  "4-8 z: zzzzzzzzzz\n" +
  "2-10 g: srnlfvgfdwcjqdspwt\n" +
  "7-10 f: fftfsblffj\n" +
  "5-8 b: sbbmbbxb\n" +
  "4-8 s: hmpvsdsssvsczpw\n" +
  "1-4 h: hghphn\n" +
  "3-7 r: glmxmlnzsfvlr\n" +
  "6-8 n: hncttfmt\n" +
  "3-5 w: wwwww\n" +
  "12-14 f: fhgfnffmmbfjlfq\n" +
  "9-10 q: qqqqqqqqgq\n" +
  "6-7 k: kkkkklkkkckkkkkfk\n" +
  "2-5 s: ssssss\n" +
  "3-8 d: ddlddddsd\n" +
  "6-9 k: kmkkvkkqkjfnkkkk\n" +
  "8-9 p: qpslppfhx\n" +
  "14-15 j: jjjjjjjjjjjjjch\n" +
  "2-5 z: rbqmznmq\n" +
  "7-8 w: wwwwwkwdwnq\n" +
  "4-7 t: cshbkttttt\n" +
  "1-2 f: fqffvffffffffffh\n" +
  "4-5 p: lfpbnvnbjsznxdpwp\n" +
  "1-2 w: wwdczgfzhv\n" +
  "16-19 p: ppppppppppsprpppppwp\n" +
  "2-11 f: mfdlhdgflgz\n" +
  "5-6 h: hhlhvj\n" +
  "2-6 n: nntjzn\n" +
  "3-4 w: wmwj\n" +
  "1-11 g: gggghgggggggggggg\n" +
  "3-4 g: jgjk\n" +
  "2-5 s: sjsss\n" +
  "2-3 h: bkhk\n" +
  "2-13 h: kbkbsjlvqxhfdwpstn\n" +
  "8-13 m: mmmmmmmkmmmmmm\n" +
  "19-20 s: sssspsssssssssssssss\n" +
  "3-7 c: jrrtcgx\n" +
  "15-18 m: mmmmmmmmmmmmmmmggm\n" +
  "5-14 x: ljxbxxxxxrnxxx\n" +
  "14-18 d: pddddjddddkqdmdddcd\n" +
  "1-19 d: tddpndddqdddddqgddd\n" +
  "7-14 b: jfbbcbbpgdbvmb\n" +
  "1-7 h: srvgwthwhhhh\n" +
  "1-4 n: xhqdfnnng\n" +
  "1-2 v: vbvvczs\n" +
  "10-14 g: gggggpgggfgggg\n" +
  "11-14 d: cnddvxddddnddldmf\n" +
  "2-3 d: tddzccmml\n" +
  "2-4 x: whfvct\n" +
  "2-5 s: cshcl\n" +
  "3-11 k: ckgkkkxzkmzjl\n" +
  "10-11 m: mmmmbmmmwkmm\n" +
  "11-12 g: gjwgggnbgggggzggjg\n" +
  "2-16 j: qkdlpxzmqkhxxxfskj\n" +
  "8-9 h: hkhxhhkqt\n" +
  "6-7 w: wwdswwwwwcqlw\n" +
  "2-9 w: bwsgvbwjrv\n" +
  "17-20 t: hknjzjzdwsqkbktkqfts\n" +
  "1-3 c: cjcsqfpgjppcccn\n" +
  "8-9 n: mnnnnznzngnnt\n" +
  "6-8 k: lgckxwkk\n" +
  "3-6 l: lsnldll\n" +
  "8-13 s: svsscsfcdsxvlksxtk\n" +
  "5-6 t: xttzsvtt\n" +
  "9-13 t: ttttstttvjbtr\n" +
  "3-4 s: sqxss\n" +
  "6-14 s: ssscsssssdssssssts\n" +
  "2-15 t: ztddqtbtttlfhttttpt\n" +
  "6-8 b: btbbbvbm\n" +
  "6-8 l: llllllllsllll\n" +
  "1-4 l: zlcv\n" +
  "10-15 f: bfstdfjfffmffffffgc\n" +
  "4-8 z: zzzbzzzvzz\n" +
  "5-7 h: qhmxhkhsjmwzkvh\n" +
  "8-12 f: lfffqffxfrfd\n" +
  "5-14 c: kcjbzhcfmrvrxkpnjd\n" +
  "5-7 b: bbbblbb\n" +
  "3-5 t: tgthtt\n" +
  "5-6 s: ssxssspsc\n" +
  "4-5 z: wzhzz\n" +
  "1-5 b: bbbbbb\n" +
  "4-11 j: sjtbrnspzndg\n" +
  "1-8 g: lbscqdrdtqgmtsg\n" +
  "4-15 c: cdccnpccscclcccccc\n" +
  "4-5 s: smsssz\n" +
  "6-9 b: bbbbbtbbqbk\n" +
  "10-13 h: hhfkhhfhhmhgq\n" +
  "3-4 s: hhsg\n" +
  "12-14 s: ssssssssssssssdss\n" +
  "5-6 w: qfxnvk\n" +
  "4-8 v: fvvvvvvvjs\n" +
  "5-11 f: ffffffffffnff\n" +
  "7-16 d: knfdxddwdddnwdjdddl\n" +
  "12-13 d: dddddddddddrw\n" +
  "16-17 w: wsxwwwwwwwwwwwwltw\n" +
  "6-10 w: wtwjcsjwhgw\n" +
  "2-7 v: spvscsxhjfjfdff\n" +
  "11-14 k: scpskhmkwkqhzm\n" +
  "16-17 m: mqmmmmmfmmzmbmmwg\n" +
  "11-12 p: pppkppppqwpc\n" +
  "2-11 d: ddgssqrdqqdd\n" +
  "5-18 z: wrghzskqlgxqmqczsxvf\n" +
  "13-14 t: tzttttvftrttttkj\n" +
  "12-16 w: hxvdgjwsbclrmrtwxc\n" +
  "1-11 x: bnxdfxgfxfq\n" +
  "9-10 k: mwsnrdbcqrvxlk\n" +
  "1-8 j: qprjjjzlj\n" +
  "17-18 f: fjfffncffffwfdxfgvfd\n" +
  "4-5 j: pjjjc\n" +
  "1-2 j: jjjh\n" +
  "2-4 v: tvpv\n" +
  "8-12 x: fxxxxxxbxxxhx\n" +
  "9-10 f: xfffffffffffffffjnf\n" +
  "1-5 k: vkkknk\n" +
  "3-4 s: qtsrfsvsvsrtc\n" +
  "5-6 z: zzmzkj\n" +
  "1-12 n: snnnnnnnnnnnnnnnn\n" +
  "2-5 m: mjmml\n" +
  "9-11 n: nnnnnnlnnngnnnv\n" +
  "2-3 x: fxxxxckxsrlwhc\n" +
  "5-15 d: rdpjlddjdrddxbddt\n" +
  "5-17 c: bccbbckwvcrmdcqcctcc\n" +
  "6-8 w: wwjwwswrwpnwgxnd\n" +
  "7-10 p: pppppppppppppp\n" +
  "3-18 h: hhlhhjnwhhbhhzhhhthj\n" +
  "2-7 b: llbbcrjbnb\n" +
  "1-6 s: ssbssfkss\n" +
  "2-3 m: zhnmd\n" +
  "10-12 t: ttlttzttllbjtttttt\n" +
  "8-10 w: wwbwwwwwmw\n" +
  "4-5 r: rrrfh\n" +
  "1-4 l: lfblrlpzzlqljlsll\n" +
  "3-4 c: cwcjmh\n" +
  "14-16 h: hhhhjhhhhxhhhlhkxhh\n" +
  "7-8 m: mmvcmqmdmkbmmmn\n" +
  "5-7 m: dwmqmmmkmkm\n" +
  "1-4 d: ddddm\n" +
  "12-16 d: dqlpddwndmrdvdmdghdh\n" +
  "18-20 v: gzqvmvzvcffwbfnvhmnq\n" +
  "4-5 c: cckcc\n" +
  "9-14 x: xxxxthxxgjbxxrx\n" +
  "6-12 z: vkxzzjzzzjfp\n" +
  "11-14 h: hczhgqsbsmtrhf\n" +
  "6-8 x: kjvscxnxfvxbmgnksxq\n" +
  "7-9 k: kvffnskdkdq\n" +
  "6-7 x: xxxxcxx\n" +
  "6-12 m: mrmmmcmjzmftgmmtm\n" +
  "13-17 f: ffqfffffpffqmfnhgbf\n" +
  "8-10 r: rrmjrktmjbrrrrsl\n" +
  "8-13 c: cccccnnrccccvqcnclcc\n" +
  "1-4 t: tttg\n" +
  "13-17 j: jpjjjjjjjjjjtjjjtjz\n" +
  "3-5 r: rrlrl\n" +
  "3-18 c: cjshpccrvfxggcfjsfwq\n" +
  "2-7 l: ldlrxqqbqllgj\n" +
  "1-3 v: bvxr\n" +
  "5-6 t: tttttt\n" +
  "17-19 b: pqbmnhbksnqqxbhlxjcr\n" +
  "4-5 p: ppppp\n" +
  "1-4 m: mmmmmm\n" +
  "1-9 b: vbtbbbbbbfbbqb\n" +
  "6-10 j: fzqldjzgdjrjt\n" +
  "6-7 w: wwwwwwzwwvww\n" +
  "8-9 r: rrrrrrrrrr\n" +
  "5-8 h: xhvjhhlhdwvh\n" +
  "7-10 w: wwwwgwlwwgwwww\n" +
  "5-9 f: lvvfcfqffv\n" +
  "4-6 n: nnnnnr\n" +
  "2-3 c: wdbq\n" +
  "19-20 l: lglllllllllllllvllrl\n" +
  "5-9 z: zzddzzzwz\n" +
  "3-4 d: dkddvdd\n" +
  "10-14 f: fmffffffrsfnfx\n" +
  "4-5 p: pvpwvqplmprp\n" +
  "4-10 c: ctclccccvbcccc\n" +
  "5-6 h: hhhzhh\n" +
  "7-14 g: ggggggggkgggggggwgg\n" +
  "8-11 b: bbrbbxbgbbb\n" +
  "3-4 q: qpxq\n" +
  "2-4 z: xkrv\n" +
  "2-3 m: mmmm\n" +
  "9-10 w: wwwwzwlzwcwwbpfrrf\n" +
  "7-12 t: kthhmbddtbhs\n" +
  "2-4 t: tttjtt\n" +
  "5-7 w: xvwwwwww\n" +
  "10-12 g: gdmgghnkmgggmwjrlgjj\n" +
  "4-6 j: jzknjjt\n" +
  "1-10 v: vvvvvvvvvc\n" +
  "8-11 w: znmpmrffmswnqw\n" +
  "7-12 w: dxpvfwcgwwwwwxwww\n" +
  "3-4 z: zbzzt\n" +
  "4-18 r: frqhkrqbcttrdqkgnr\n" +
  "9-12 s: dssxrzjsfssv\n" +
  "2-4 w: fwjw\n" +
  "11-13 r: kdrrrrrrvrrrqrprr\n" +
  "7-10 g: gggggggggg\n" +
  "1-5 v: vdvvv\n" +
  "19-20 s: vmswvsbspsgsvszssbss\n" +
  "4-5 q: qqqqqq\n" +
  "6-9 l: llrdllwlwlll\n" +
  "9-11 m: mmmdmmmmkmhgmkmmmm\n" +
  "1-3 g: sgfg\n" +
  "12-14 g: gggggggggrggpgggrb\n" +
  "6-9 x: zdzplkrxxkkrjpxnsdzl\n" +
  "14-19 h: htclqdvhdzqhxbhzhkh\n" +
  "2-4 m: wmmmt\n" +
  "3-4 p: sjpp\n" +
  "3-4 h: hhrx\n" +
  "2-3 r: zhlzpzc\n" +
  "14-20 j: nffzpjmqrjbjjfjjmcjl\n" +
  "4-6 w: wmpjwzzd\n" +
  "7-8 q: qqqqqqqq\n" +
  "4-5 n: rgcvfnbn\n" +
  "3-4 g: qgmcgs\n" +
  "4-8 v: vvzlzxhclv\n" +
  "7-8 g: szsgfzgqjnj\n" +
  "12-15 w: wwwwwwwwwwwwkwd\n" +
  "11-12 t: ttttjtttttpz\n" +
  "5-6 q: gdmrqq\n" +
  "5-7 w: nwwwwwrw\n" +
  "1-4 s: srpm\n" +
  "14-18 w: wwwwwfwwwwwwwnwwwrw\n" +
  "7-9 z: zzzsznjzrfzw\n" +
  "3-18 v: vvxvvvkvvvbvvgjvvvv\n" +
  "2-16 p: mmnsdmhhkfqplzcwq\n" +
  "1-2 h: hhlmvhw\n" +
  "7-8 n: nnnznqnn\n" +
  "3-4 n: hnnn\n" +
  "5-6 p: zvbdhnpkcpggvlxppp\n" +
  "3-4 l: lljgll\n" +
  "1-5 d: ndddmddddd\n" +
  "3-4 t: dttt\n" +
  "4-5 m: wmmzm\n" +
  "6-8 m: mhmmmvmwm\n" +
  "8-11 b: wxzvmmvbxqbjb\n" +
  "18-19 x: xdtszmmqxlxzvxgxwvj\n" +
  "15-19 r: rrrrrrrpwfrrrrrrrrrr\n" +
  "9-17 j: jjjjjjrjjjjjjvjjjjqj\n" +
  "2-5 t: nmxwtthqstg\n" +
  "9-17 h: chjkngjkkrnkhgtgv\n" +
  "2-4 r: rrrr\n" +
  "10-16 l: lpdlllmsllfkllll\n" +
  "2-4 g: gxgmg\n" +
  "4-5 h: rnhhh\n" +
  "2-5 j: jqnvqlntsccr\n" +
  "2-6 x: dxdxwxfxfnxx\n" +
  "5-19 s: fsnpsdhkbqnscbdjphf\n" +
  "5-10 v: hclvbnmvwvvcvsgxbdcv\n" +
  "2-10 r: gfczjcpjbdlf\n" +
  "4-9 m: mmmxmmmmmm\n" +
  "4-14 b: bpjgdxbbbvbgbbbb\n" +
  "6-8 w: qhwwbwwww\n" +
  "7-10 x: wjxzxxxfxxs\n" +
  "7-9 w: hwjdwfjgqcwhlwwwwg\n" +
  "3-8 v: vbvwpnmv\n" +
  "1-9 h: chhhhhhdnh\n" +
  "3-4 l: qgllflwhsbq\n" +
  "6-9 q: qzqkqqzqqlfmfq\n" +
  "3-12 m: mmwmvmmmmdmmzlbtmr\n" +
  "3-5 n: nnknwn\n" +
  "7-8 b: bbnbbbxs\n" +
  "2-4 f: fvljfff\n" +
  "12-15 w: wwwwwrwwwwwwwwvwwww\n" +
  "2-4 g: gggmg\n" +
  "1-2 w: wwxwqw\n" +
  "11-18 s: sssssssssscqsssssn\n" +
  "12-15 r: rrcrrrrrrrwlbgrh\n" +
  "9-14 t: ttttwsttrnttthtt\n" +
  "4-5 n: nnnnnnnn\n" +
  "15-16 w: wwwwwwwwwtwwwdwww\n" +
  "7-12 g: qfgjwcggglgggwmlhr\n" +
  "1-15 z: zzsphzzzvzzzbpzzz\n" +
  "14-16 l: llllllllxlllljlsll\n" +
  "3-4 x: xxxx\n" +
  "3-6 w: dhwpjw\n" +
  "2-7 v: zvvkxcvbtwx\n" +
  "2-5 x: whpfx\n" +
  "4-6 f: mfndfc\n" +
  "5-7 z: tznzzzn\n" +
  "3-5 l: jtllld\n" +
  "15-17 d: jbdrdnlqdbdlvzwhbdz\n" +
  "14-18 d: ddddddddddddddddddd\n" +
  "3-4 c: vlvsqxcmjsk\n" +
  "10-14 b: bpbhbbdvblbsfbbrdb\n" +
  "6-7 g: dgmchcbmhhxcbvg\n" +
  "11-15 d: ddddddddddndddqddddd\n" +
  "3-11 g: ggxlggggggfgg\n" +
  "3-5 g: gcrgw\n" +
  "4-8 q: xqlqrqqkk\n" +
  "3-4 x: zrqndxxxf\n" +
  "4-9 l: llllllllcllglll\n" +
  "4-6 d: bdddddztdbd\n" +
  "7-9 s: zkghrssxm\n" +
  "4-6 x: xgncxfx\n" +
  "8-9 c: cccccccwn\n" +
  "9-10 m: mmmzmmmmmmhvm\n" +
  "4-5 c: cvhcc\n" +
  "2-5 k: kfkqgxqfk\n" +
  "16-18 s: ssssssssssksssssss\n" +
  "4-5 k: zbknk\n" +
  "3-4 h: hjdhcfsv\n" +
  "4-6 f: lfrfdfhfqf\n" +
  "2-11 k: kkkkkkktkkkkkk\n" +
  "1-9 f: fkwtffhffxftdfz\n" +
  "8-15 b: bbbbprztvbbbkbbbbbb\n" +
  "6-10 s: ssssfwssswgk\n" +
  "11-12 t: trcthtmljttv\n" +
  "3-4 s: svss\n" +
  "6-8 p: ptpppzpldvcdbbbpwmjg\n" +
  "11-17 x: cxpqbxxxxbxxxqxxn\n" +
  "11-14 z: pzzzzwpxnzzkzzz\n" +
  "6-7 c: ccccccc\n" +
  "1-2 z: grzzz\n" +
  "8-10 d: xgmswdsvtb\n" +
  "7-8 c: kcccccdp\n" +
  "12-13 f: btcnxsclqznxmf\n" +
  "4-11 k: grhkjkkkkkkkkpksktkk\n" +
  "15-16 z: zzzzzzzzszzzzzzz\n" +
  "8-11 v: vvvvvvvgvvlvvvvv\n" +
  "1-2 c: qqccc\n" +
  "2-4 w: nvkgzdfw\n" +
  "3-12 f: bfvpftfffwdfff\n" +
  "5-6 h: wghnhtvzhhz\n" +
  "4-6 v: vpvmvp\n" +
  "5-9 z: nfgwzzzszz\n" +
  "10-11 b: bbbxbbbbbbbb\n" +
  "6-7 g: ggnggzw\n" +
  "2-6 c: bcrccc\n" +
  "1-13 s: dsssssssssssls\n" +
  "1-6 j: fjjjjcj\n" +
  "4-14 p: pzvfnpfppblfjngpkzj\n" +
  "1-2 p: pppv\n" +
  "4-5 t: gttsktt\n" +
  "3-13 w: wwwrbwwwwwcwwwrwxg\n" +
  "12-14 r: zrtrdrrrjrhrmrl\n" +
  "5-6 b: bnbbbwbbw\n" +
  "13-19 g: ggqbhgfggfpgqgggggx\n" +
  "11-12 b: bbbbbkbbbbnp\n" +
  "10-11 c: hcvccchqshj\n" +
  "6-8 k: krvlcfkrxx\n" +
  "5-13 d: dddddddddddddd\n" +
  "5-7 w: wwwzbwkhvwwm\n" +
  "6-10 z: zzzzznzzzrzz\n" +
  "11-12 h: hhhhhhhthfcr\n" +
  "9-13 t: ttttsxtttkgtttgtt\n" +
  "11-13 r: nrrrrrrrrrprtrrrrrrr\n" +
  "16-17 l: kllllhlllllllllzdl\n" +
  "4-6 w: wwjwvw\n" +
  "1-3 j: mjnxbqvzfjgjsjr\n" +
  "7-8 t: pltpspvt\n" +
  "5-13 m: lmzmmnqfmmjmtm\n" +
  "1-15 d: djxhfqjwjmdndhg\n" +
  "4-6 r: hkrrrrgsdsx\n" +
  "1-7 r: srrrrrrrsprh\n" +
  "3-6 g: dbgtqwkwkgzqxbgbgkh\n" +
  "15-18 s: sssslrsspssssszssp\n" +
  "8-11 q: qqvkqpdqdqqz\n" +
  "1-3 c: cccscccc\n" +
  "5-9 d: wpfzlqnsdrtlvwnd\n" +
  "7-9 f: qrdblxfnf\n" +
  "3-4 z: flzz\n" +
  "11-12 c: ccccccccccpwc\n" +
  "3-4 v: ltjwvcv\n" +
  "13-15 p: ppppppppppppfpp\n" +
  "14-15 r: zrrrrrrrbrrrrrkrr\n" +
  "2-5 n: lnwnnsmfd\n" +
  "4-7 t: ttctrtt\n" +
  "5-6 w: hsfpwcwrfwxmwww\n" +
  "5-8 b: bbbbmbbfbb\n" +
  "1-3 z: czzp\n" +
  "4-6 h: hhbhhh\n" +
  "16-18 j: jjjjjjjjjjjjjjjjjq\n" +
  "1-2 n: zdlwqzlnnp\n" +
  "5-16 m: mmmmxmmmmmmmmmmjm\n" +
  "3-5 h: hhlfhghhhjh\n" +
  "2-6 f: vkfbpf\n" +
  "5-6 j: jjjjjjj\n" +
  "4-8 q: qdmzqlln\n" +
  "6-7 x: xpxxxjtxs\n" +
  "2-5 z: znzzxq\n" +
  "8-13 j: jjjjwvvjcjjjkj\n" +
  "2-7 x: xkxwxxncxtxvxxlxr\n" +
  "4-13 m: zrxmqfmmjgcgqwk\n" +
  "2-4 b: bqbbbb\n" +
  "2-3 j: gjjlv\n" +
  "14-17 n: nnnqnnntnnnnndnnmnnn\n" +
  "3-8 c: tlcmcccx\n" +
  "2-7 c: ccmlbscmb\n" +
  "7-8 l: ljflbgll\n" +
  "2-11 p: dqkzvmptdgchclbw\n" +
  "7-12 w: wwwwwwwwwwww\n" +
  "1-10 r: htpmgskvrzr\n" +
  "1-4 m: fndmmmmztmcgmx\n" +
  "3-4 t: qmtttzqtt\n" +
  "11-17 g: zggggdgdglqfsgqxggg\n" +
  "2-10 c: ccccfkvxcc\n" +
  "13-15 g: ggggggggggggnggzgg\n" +
  "4-14 z: zzzzzzzzzlzzzzzzzz\n" +
  "4-13 g: ggglggggggggqg\n" +
  "12-13 x: xzxxxxxxxxxkxx\n" +
  "3-7 s: sssssssjss\n" +
  "9-11 j: jjtjrjzjjhjjkbjjjbjt\n" +
  "4-6 r: rkrfrrrrr\n" +
  "5-6 q: qmqcgqqq\n" +
  "4-17 t: tttmtttcttttttttttt\n" +
  "2-4 d: fsbdddpdd\n" +
  "11-15 b: xbbbbbbbbbbbrbqpbb\n" +
  "4-6 s: lkqsqwkszzsjst\n" +
  "13-14 l: lllllllllllllllllll\n" +
  "12-15 t: btlttmbthtttttdtt\n" +
  "9-12 q: mkcqrnfqxqnqskpq\n" +
  "3-5 m: stmmmgqjfv\n" +
  "5-11 v: vvlgzvvvvvv\n" +
  "2-6 n: znntrnhnntbpjkgnqv\n" +
  "7-8 d: sgmddfddjrtv\n" +
  "6-10 k: kqkkbnkkpdk\n" +
  "5-7 n: nnnznnngnl\n" +
  "9-16 q: qqqqqqqqjqqqqqqbqqqq\n" +
  "2-4 w: bwww\n" +
  "9-11 c: jfpvdqftgqx\n" +
  "5-11 c: ccccckcccfccccc\n" +
  "1-2 c: ccbsvl\n" +
  "1-5 d: ddmmd\n" +
  "2-8 j: ntjhkjjmjcj\n" +
  "5-6 p: ppppskpkpp\n" +
  "4-8 t: ztptgptzmtttw\n" +
  "5-6 k: gvjzkmdkfmxnlq\n" +
  "17-18 f: ffffffffffffffffdf\n" +
  "1-13 s: sssbhztsnssgs\n" +
  "3-6 v: mlvvvfvwxvvxv\n" +
  "6-11 p: npkcbslzpvtkjp\n" +
  "2-4 m: gbsjxmjxcdsdnv\n" +
  "16-17 b: bcbbbbbbbbbfbbbbvbbb\n" +
  "17-18 h: lmshsjxbbhhrqhfqchkh\n" +
  "1-3 l: llllk\n" +
  "5-8 h: dhhwhhhnhh\n" +
  "9-12 f: ffdhpzffkffpfcffjf\n" +
  "1-5 k: khbfkkc\n" +
  "1-8 p: ndkpxvpgpppp\n" +
  "1-7 t: tljjkttqptttvt\n" +
  "16-17 t: tttttttttrttttttt\n" +
  "13-18 z: ztzzzzgzzzzglzzndjzf\n" +
  "13-15 q: qqqqqqqqqqqqqqqqq\n" +
  "6-8 v: vvvvvvvv\n" +
  "10-15 q: fqcxlxvhvgfzxwvqv\n" +
  "4-12 g: btdgdglbprjg\n" +
  "3-5 t: gttjt\n" +
  "1-11 w: twwwwwwwwwnwww\n" +
  "2-3 f: jgbfcfbfftccffff\n" +
  "1-2 r: rrrnwr\n" +
  "11-16 r: rrrrrrrrrrrrrrrr\n" +
  "1-16 q: qqqqqqqqqqqqqqqqqqqq\n" +
  "7-16 z: zwzzzzfzzzzzzzzz\n" +
  "10-11 f: fflfmfrjfhjffff\n" +
  "1-5 t: npxgd\n" +
  "7-8 n: nknnnngbxd\n" +
  "4-6 k: kkkkkkk\n" +
  "5-19 d: xtdddjxfvxgddddndndq\n" +
  "8-12 s: vstssxssssss\n" +
  "3-6 f: tlfftfxqhbltbrg\n" +
  "17-19 d: ddddddddddddddddtdc\n" +
  "2-9 q: qqqqnqgbq\n" +
  "8-14 k: wknbkkkbkzkgkdkk\n" +
  "17-18 n: nnnntnnvnnnnnnnnnnnn\n" +
  "15-16 p: ppppppppppppppppp\n" +
  "2-4 h: hwhhhh\n" +
  "4-9 d: ddddddddddd\n" +
  "1-8 s: sssssssrs\n" +
  "14-15 z: zfzzzzzzzcfzzzz\n" +
  "5-6 k: kkkkkkk\n" +
  "5-6 x: xxxxxvx\n" +
  "18-19 r: rrrrjrkbttrjpfjqftm\n" +
  "11-12 f: fffffffffsff\n" +
  "11-17 z: hwzdfvbpbxzfpjwmzq\n" +
  "1-11 m: mxkmnxfbtnmvmtzdqjl\n" +
  "3-4 d: ddjg\n" +
  "17-18 b: jnlntbblbbqbkqmbbb";
