export default "Valve AA has flow rate=0; tunnels lead to valves RZ, QQ, FH, IM, VJ\n" +
  "Valve FE has flow rate=0; tunnels lead to valves TM, TR\n" +
  "Valve QZ has flow rate=19; tunnels lead to valves HH, OY\n" +
  "Valve TU has flow rate=17; tunnels lead to valves NJ, IN, WN\n" +
  "Valve RG has flow rate=0; tunnels lead to valves IK, SZ\n" +
  "Valve TM has flow rate=0; tunnels lead to valves FE, JH\n" +
  "Valve JH has flow rate=4; tunnels lead to valves NW, QQ, TM, VH, AZ\n" +
  "Valve NW has flow rate=0; tunnels lead to valves JH, OB\n" +
  "Valve BZ has flow rate=0; tunnels lead to valves XG, XF\n" +
  "Valve VS has flow rate=0; tunnels lead to valves FF, GC\n" +
  "Valve OI has flow rate=20; tunnel leads to valve SY\n" +
  "Valve IK has flow rate=0; tunnels lead to valves RG, TR\n" +
  "Valve RO has flow rate=0; tunnels lead to valves UZ, YL\n" +
  "Valve LQ has flow rate=0; tunnels lead to valves IZ, PA\n" +
  "Valve GG has flow rate=18; tunnels lead to valves GH, VI\n" +
  "Valve NJ has flow rate=0; tunnels lead to valves TU, UZ\n" +
  "Valve SY has flow rate=0; tunnels lead to valves OI, ZL\n" +
  "Valve HH has flow rate=0; tunnels lead to valves QZ, WN\n" +
  "Valve RZ has flow rate=0; tunnels lead to valves AA, UZ\n" +
  "Valve OF has flow rate=0; tunnels lead to valves YL, IZ\n" +
  "Valve IZ has flow rate=9; tunnels lead to valves OF, FH, VH, JZ, LQ\n" +
  "Valve OB has flow rate=0; tunnels lead to valves UZ, NW\n" +
  "Valve AH has flow rate=0; tunnels lead to valves FF, ZL\n" +
  "Valve ZL has flow rate=11; tunnels lead to valves SY, VI, AH\n" +
  "Valve BF has flow rate=0; tunnels lead to valves PA, YL\n" +
  "Valve OH has flow rate=0; tunnels lead to valves CU, JZ\n" +
  "Valve VH has flow rate=0; tunnels lead to valves IZ, JH\n" +
  "Valve AZ has flow rate=0; tunnels lead to valves JC, JH\n" +
  "Valve XG has flow rate=0; tunnels lead to valves BZ, PA\n" +
  "Valve OY has flow rate=0; tunnels lead to valves PZ, QZ\n" +
  "Valve IM has flow rate=0; tunnels lead to valves FM, AA\n" +
  "Valve GO has flow rate=0; tunnels lead to valves VJ, TR\n" +
  "Valve YL has flow rate=8; tunnels lead to valves JC, RO, OF, BF, FM\n" +
  "Valve TY has flow rate=0; tunnels lead to valves SZ, TS\n" +
  "Valve UZ has flow rate=5; tunnels lead to valves OB, NJ, RO, RZ, GC\n" +
  "Valve XF has flow rate=21; tunnel leads to valve BZ\n" +
  "Valve RY has flow rate=0; tunnels lead to valves TR, FF\n" +
  "Valve QQ has flow rate=0; tunnels lead to valves JH, AA\n" +
  "Valve TS has flow rate=0; tunnels lead to valves TY, FF\n" +
  "Valve GC has flow rate=0; tunnels lead to valves VS, UZ\n" +
  "Valve JC has flow rate=0; tunnels lead to valves AZ, YL\n" +
  "Valve JZ has flow rate=0; tunnels lead to valves IZ, OH\n" +
  "Valve IN has flow rate=0; tunnels lead to valves TH, TU\n" +
  "Valve FM has flow rate=0; tunnels lead to valves IM, YL\n" +
  "Valve FH has flow rate=0; tunnels lead to valves AA, IZ\n" +
  "Valve VJ has flow rate=0; tunnels lead to valves AA, GO\n" +
  "Valve TH has flow rate=0; tunnels lead to valves CU, IN\n" +
  "Valve TR has flow rate=7; tunnels lead to valves FE, IK, RY, GO\n" +
  "Valve GH has flow rate=0; tunnels lead to valves GG, FF\n" +
  "Valve SZ has flow rate=10; tunnels lead to valves RG, TY\n" +
  "Valve PA has flow rate=16; tunnels lead to valves XG, LQ, BF\n" +
  "Valve PZ has flow rate=0; tunnels lead to valves CU, OY\n" +
  "Valve VI has flow rate=0; tunnels lead to valves ZL, GG\n" +
  "Valve CU has flow rate=22; tunnels lead to valves PZ, OH, TH\n" +
  "Valve WN has flow rate=0; tunnels lead to valves TU, HH\n" +
  "Valve FF has flow rate=13; tunnels lead to valves VS, RY, AH, TS, GH";
